################################################################################
# BMC Software, Inc.
# Confidential and Proprietary
# Copyright (c) BMC Software, Inc. 2001-2012
# All Rights Reserved.
################################################################################

development:
  bucket_name: appname_development
  access_key_id: 
  secret_access_key: 

test:
  bucket_name: appname_test
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: appname
  access_key_id: 
  secret_access_key: 
